# Generated by Django 5.2.3 on 2025-06-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('CS', 'Casual shoe Men'), ('CW', 'Casual Shoe Women'), ('BT', 'Boots'), ('SS', 'Sports Shoe'), ('KD', 'Kids'), ('JC', 'Jersey'), ('TS', 'T-Shirts'), ('PN', 'Pants')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
                ('product_quantity', models.FloatField()),
                ('modified_date', models.DateField(auto_now=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
